// Protocol definitions and handlers - Phase 1.1
// 
// Safety: All protocols implement authentication and validation
// Privacy: Protocol messages don't leak sensitive information
// Transparency: Protocol interactions are logged

pub mod messages {
    // Re-export protobuf generated code
    // TODO: Include generated protobuf code here
    
    pub mod node {
        // Placeholder for generated node.proto code
        // Will be generated by build.rs
    }
}

// Protocol version for compatibility checking
pub const PROTOCOL_VERSION: &str = "zephyrfs/1.0.0";